services:
  app:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - .:/app
      - ${DB_IMAGE_PATH}:/app/data  
    environment:
      - PYTHONUNBUFFERED=1
      - DB_IMAGE_PATH=/app/data
    command: ["python", "demo.py"]